### ISSUE TITLE
Wrong port and protocol for accessing a file from the AAS Server

### ISSUE THREAD

**Issue by CMor1184** [eclipse-basyx/basyx-applications#25] opened 2023-03-25 21:40 UTC
I am running the BaSyx docker containers (registry, server, gui) in a docker compose environment and traefik as a reverse proxy with SSL termination.

Everything is working fine except the download of a File from the element details view, because the wrong domain is pre-filled here. In the input field, instead of "https://aas-server.example.com/aasServer/files/aasx/Document/operating-manual-xp-xpc-xpk-en.pdf" - "http://aas-server.example.com:4001/aasServer/files/aasx/Document/operating-manual-xp-xpc-xpk-en.pdf" is pre-filled.
If I change the domain manually the download and pdf preview is working. I think the initial pre-filled info comes from the context.properties file from the AAS server, right? But thats actually the internal docker port and non TLS. 

<img width="1442" alt="image" src="https://user-images.githubusercontent.com/36864887/227742929-2294b50c-ebee-433e-bad9-b26a3626b78d.png">

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/36864887/227743692-9fd3a8c7-abfe-4a1f-8883-d65a95918c83.png">

<img width="570" alt="image" src="https://user-images.githubusercontent.com/36864887/227742983-a3d7e295-4d03-46f6-b023-2098a20a97d6.png">

**Comment by aaronzi** [comment] 2023-03-25 22:16
The issue seems to me to be more related to the AAS server. I'm adding @FrankSchnicke to the conversation for this. He knows best about the implementation and intricacies of the AAS server.

**Comment by FrankSchnicke** [comment] 2023-03-28 06:03
For changing the external URL/Port to be used in the registry, there's the **registry.host** entry in the [aas.properties](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_AAS_Server_/_Features_/_Registry_Integration).

**Comment by CMor1184** [comment] 2023-03-28 15:28
yes that is configured, but the only issue I have is the pre-filled "File path", see screenshot above.

![image](https://user-images.githubusercontent.com/36864887/228288892-9e87fc74-7852-4334-941d-9ccbf31daa7e.png)

**Comment by FrankSchnicke** [comment] 2023-03-29 05:38
Thanks for pointing this out. After investigating, it seems like the file path handling does not use the registry.host entry correctly. We will provide a bugfix soon.

**Comment by FischerRene** [comment] 2023-05-04 06:58
As I can't replicate the issue, a few more questions:
1. What versions of the docker containers did/do you use?
2. How did you configure the containers?

My guess would be that you either have not added the aas.properties file correctly to the aas server container (maybe a typo?) or you used docker environment variables that have overwritten the properties from the file.

As a reference, [here is a simple compose file with environment variables](https://github.com/eclipse-basyx/basyx-java-examples/blob/main/basyx.docker/simple-deployment-with-gui/compose.yaml). To use the aas.properties for example you would need to mount it into the container using a volume just like the AASX-files in the example.

**Comment by adankert70** [comment] 2023-05-09 07:28
![image](https://user-images.githubusercontent.com/56963150/237025385-15f0e42d-1cef-4859-bf55-8c779d2c9177.png)

**Comment by adankert70** [comment] 2023-05-09 07:32
As you can see the initial port and protocol issue has been ironed out. Now the issue is the issue seems to be file url/path and/or availability of the files on the server side.

**Comment by FischerRene** [comment] 2023-05-10 10:02
> I use the latest container available at any given time. We use a CosmosDB as backend for both registry and server, and we run the containers in our Kubernetes-based platform. I upload the aasx files using the API and POST method. After I do that I see the files both in the server and the registry (thanks to the new version!) But the binary files included in the aasx are nowhere to be found, and not found errors are shown in the Web UI.
> 
> If I use this sample aasx file: https://admin-shell-io.com/samples/aasx/17_ABB.aasx It uploads fine to the server and the server registers it to the registry. I connect the UI to the registry and I can see the ABB asset admin shell. I can browse the submodels and see the various properties. If I open the Nameplate submodel and try to look at the "File" property I can see that there is a URL specified on the "Download" button: https://our-server/shells/aas/submodels/Nameplate/submodel/submodelElements/Marking_CE/File/File
> 
> The server seems to be correct, however the path returns a 404. (I would expect it to be a image filename there)
> 
> Same for the "Document" submodel. The download link for property "File" is: https://ourserver/shells/aas/submodels/Document/submodel/submodelElements/ManualEN/File/File and it returns a 404.
> 
> I have tried using the UI to upload files but that fails: Error uploading File-SubmodelElement "File"!
> 
> Are binary files/attachment supported with the MongoDB backend?
> 
> I have tried other sample AASX files, but with the same result. Everything works as expected, apart from the binary files/attachments.

From my perspective this seems to be a mismatch between the CosmosDB and MongoDB design, but I'm not an expert on CosmosDB, so I might be wrong here.
According to [the MongoDB comparison](https://www.mongodb.com/mongodb-vs-cosmos-db) (might have a slight bias as it's the company website) documents might be handled differently as the maximum size is only 2MB instead of the 16MB supported by MongoDB. My guess is it is simply not supported by the library we use to communicate with MongoDB.
See the implementation [here](https://github.com/eclipse-basyx/basyx-java-components/tree/main/basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb) with the filehandling on the [SubmodelAPI level](https://github.com/eclipse-basyx/basyx-java-components/blob/main/basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/java/org/eclipse/basyx/components/aas/mongodb/MongoDBSubmodelAPI.java).

If you this is not a solution to the issue, please feel free to create a new issue in the [BaSyx Java Components](https://github.com/eclipse-basyx/basyx-java-components) Repository and we can go on from there. This way we avoid mixing up the issues for different purposes. 😄 

If this is a feature you like to see in the future, please feel free to either contribute to the open source project or come to one of our [BaSyx Open Hours](https://www.iese.fraunhofer.de/en/customers_industries/digitalisierung-produktion/industrie40/basyx_open_hour.html) or shoot us a mail and we can see how it fits in the roadmap.

**Comment by FrankSchnicke** [comment] 2023-06-26 09:11
@adankert70 , @CMor1184 is this issue still relevant? If no, I will close this ticket in the coming days

**Closed** 2023-06-30 05:47 UTC
